### ISSUE TITLE
Upload Video Not Working

### ISSUE THREAD

**Issue by valini98** [avscms/avscms#29]
im trying to upload video but not working, progressbar not working and direct to https://domain.com/upload/video?status=1 , show notification "Video uploaded successfully!" , video not showing in Manage Video and Conversion Queue.
Im cek error log and get this error
2024/03/30 14:03:21 [error] 442215#0: *2336 FastCGI sent in stderr: ＂PHP message: PHP Warning: filesize(): stat failed for /www/wwwroot/domain/media/videos/vid/1820797233_1711803691. in /www/wwwroot/domain/modules/upload/video.php on line 64＂ while reading response header from upstream, client: 172.70.188.61, server: domain.com, request: ＂POST /upload/video HTTP/1.1＂, upstream: ＂fastcgi://unix:/tmp/php-cgi-73.sock:＂, host: ＂domain.com＂, referrer: ＂[https://domain/upload/video?status=1＂](https://domain/upload/video?status=1%EF%BC%82)

Webserver Using : Nginx
PHP Ver 7.3

**Comment by valini98** [comment]
Fixed!

**Comment by abdiisadisdnsk** [comment]
Hey, How did you fix this error?

**Comment by fernnje** [comment]
> > Hey, How did you fix this error?
> 
> Using php7.3-fpm

can you explain detail how to fix it?

**Comment by valini98** [comment]
I changed the PHP version to 7.3-fpm 
And the most important thing in the config.paths.php file, in the base URL section, if your website uses https, replace it with https, because that triggers the ajax function.

**Comment by fernnje** [comment]
> I changed the PHP version to 7.3-fpm And the most important thing in the config.paths.php file, in the base URL section, if your website uses https, replace it with https, because that triggers the ajax function.

I was already use https in the config.paths.php but I still get error when uploading..like your problem, Idk how to use php 7.3-fpm, can you give me tutorial installing that?

**Comment by valini98** [comment]
> > I changed the PHP version to 7.3-fpm And the most important thing in the config.paths.php file, in the base URL section, if your website uses https, replace it with https, because that triggers the ajax function.
> 
> I was already use https in the config.paths.php but I still get error when uploading..like your problem, Idk how to use php 7.3-fpm, can you give me tutorial installing that?

Have you removed exec() from the exceptions in php.ini?
